mpfr_pi: mpfr_pi.c mpfr_pi_impl_ramananujan_1910.c mpfr_pi_generic.h stringify.h subr.h subr.c
	cc -o mpfr_pi mpfr_pi.c mpfr_pi_impl_ramananujan_1910.c subr.c -lmpfr -lgmp

clean:
	rm -f mpfr_pi *.o core *.log *.out
