mpfr_pi: mpfr_pi_ramananujan.c mpfr_pi_impl_ramananujan_1910.c stringify.h subr.h subr.c
	cc -o mpfr_pi mpfr_pi_ramananujan.c mpfr_pi_impl_ramananujan_1910.c subr.c -lmpfr -lgmp

clean:
	rm -f mpfr_pi *.o core *.log *.out
